SecRule REQUEST_HEADERS:User-Agent "!@rx allowlist-ua.data" \
    "id:1337000,\
    phase:1,\
    block,\
    capture,\
    t:none,\
    msg:'Found User-Agent not on the allowlist',\
    severity:'CRITICAL'"